# Generated by Django 5.2.16 on 2026-07-12 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='title in url')),
                ('is_active', models.BooleanField(verbose_name='is active?')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده است؟')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(db_index=True, max_length=300)),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('short_desc', models.TextField(blank=True, max_length=360, null=True, verbose_name='توضیحات اصلی')),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('is_delete', models.BooleanField(verbose_name='حذف شده است؟')),
                ('category', models.ManyToManyField(related_name='products_category', to='product.productscategory', verbose_name='کتگوری')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=300, verbose_name='کپشن')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
    ]
